### ISSUE TITLE
https instead of http for links at  http://www.lod-cloud.net/#

### ISSUE THREAD

**Issue by salgo60** [lod-cloud/lod-cloud-draw#1]
On http://www.lod-cloud.net/#

when I click in the diagram I get a 
https://www.lod-cloud.net/dataset/wikidata
instead of a http link 
http://www.lod-cloud.net/dataset/wikidata

**Comment by jmccrae** [comment]
The issue is with the certs on the lod-cloud.net not being installed... not a bug with this repo
