### ISSUE TITLE
IPFS links status?

### ISSUE THREAD

**Issue by berezovskyi** [lod-cloud/lod-cloud-draw#10]
Hi,

I am very new to IPFS. I wanted to check if the RDF files are still available from IPFS but I can't seem to get metadata about any of them:

```sh
cat lodcloud.csv | cut -d, -f1 | xargs -P 64 -t -n 1 ipfs ls -v
```

Cf. using a CID from the tutorial:

```sh
❯ ipfs ls -v /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG
Hash                                           Size Name
QmZTR5bcpQD7cFgTorqxZDYaew1Wqgfbd2ud9QqGPAkK2V 1677 about
QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y 189  contact
QmY5heUM5qgRubMDD1og9fhCPA6QdkMp3QCwd4s7gJsyE7 311  help
QmdncfsVm2h5Kqq9hPmU7oAVX2zTSVP3L869tgTbPYnsha 1717 quick-start
QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB 1091 readme
QmTumTjvcYCAvRRwQ8sDRxh8ezmrcr88YFU7iYNroGGTBZ 1016 security-notes
```

**Comment by jmccrae** [comment]
Hi, the server that hosts our IPFS is currently down, so it is probably not working.

I am closing the issue as it is not related to this repository and forwarding to the colleague who implemented the IPFS work.
