### ISSUE TITLE
thread 'main' panicked at 'Settings file does not exist

### ISSUE THREAD

**Issue by icgw** [lod-cloud/lod-cloud-draw#3]
When I run the program it shows the message as follows:
```
thread 'main' panicked at 'Settings file does not exist: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I am not good at rust, and not sure how to deal with it?

Could you give me a promising solution? Thanks in advance.

**Comment by jmccrae** [comment]
Sorry, the error message is not very clear with all the Rust internal text here. The message was "Settings file does not exist". This is specified with the `-e` flag or defaults to `clouds/lod-cloud-settings.json`.
