### ISSUE TITLE
Cannot run tool due to missing lib libcgfam.so

### ISSUE THREAD

**Issue by frmichel** [lod-cloud/lod-cloud-draw#4]
Hey,

I've compiled the lod-cloud-draw on a CentOS 7 machine, using the last rust + cargo distribution. 
gcc-fortran was pre-installed with gcc 4.8.5.

Compilation succeeds despite a few warnings. When I run the binary I get this error:

    ./lod-cloud-draw: error while loading shared libraries: libcgfam.so: cannot open shared object file: No such file or directory

I googled that but can't find anything about this libcgfam.so (anything at all with Google...). 

Any suggestions?

Thx,
   Franck.

More details of gfortran in case it may help:

```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
```

**Comment by jmccrae** [comment]
This seems to be an issue with Cargo.

The workaround is to start the app with

```
cargo run
```

**Comment by jmccrae** [comment]
This is actually my bug. I pushed a quick fix for this.

I created an issue in the dependency project https://github.com/noshu/rustimization/issues/7 to report the original error

**Comment by frmichel** [comment]
Ok this is great, it is running right now.  I will see the result when it completes

Last question: the file at https://www.lod-cloud.net/lod-data.json does not seem to be the last version. How can I get the very last status of the database?

**Comment by jmccrae** [comment]
There is a scripts in `scripts/get-data.py` that downloads the files from the database. However, it also does a lot of other checks so can take hours to run.

**Comment by frmichel** [comment]
Ok I'll have a look to that script.

In the meantime the processing has completed with an error:

```
At iterate 5756    f=  6.89163D+04    |proj g|=  1.25811D-05

 Bad direction in the line search;
   refresh the lbfgs memory and restart the iteration.

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
 2598   5757   6010      3     0     0   1.258D-05   6.892D+04
  F =   68916.269973574847     

ABNORMAL_TERMINATION_IN_LNSRCH                              

 Line search cannot locate an adequate point after 20 function
  and gradient evaluations.  Previous x, f and g restored.
 Possible causes: 1 error in function or gradient evaluation;
                  2 rounding error dominate computation.

 Cauchy                time 0.000E+00 seconds.
 Subspace minimization time 8.136E-02 seconds.
 Line search           time 4.568E+03 seconds.

 Total User time 4.593E+03 seconds.

ERROR: ABNORMAL TERMINATION
Final well size: 1076.198
```

I've run it on a VM with 2 CPU cores and 4GB memory. Is it too little?

**Comment by frmichel** [comment]
Oh yes it has produced the diagram indeed. Given the error, I'm not eve looked for it, sorry about that.
Ok so that great, now I'm going to try and get the latest json file with the scripts/get-data.py script. Let you know.

Thx a lot!

**Comment by frmichel** [comment]
Hey @jmccrae , me again ;)

Instead of going through the get_data.py script, I've run lod-cloud-draw with the latests json file from https://lod-cloud.net/extract/datasets.

Now the tools stops immediately with message "Data contains a JSON error", nothing more. I've checked the file with some other tool, it looks good to me. 

I've also run get_data.py after deactivated all checks, so that it only rewrites the json file at the end. Same result.

Any ideas? Can you give it a try?

**Comment by frmichel** [comment]
Thx John, ok got it. 

So I've changed script get_data.py to do no query at all, instead I create a fake requests.Response() object with status 200 so that everything succeeds.
In check_url() and check_example(), I set media_type to the empty string.

Now that generates the lod-data.json file in a second.

But when I run the diagram generation, I still get this "Data contains a JSON error". And I'm not familiar with rust. Can you help me there?

**Comment by frmichel** [comment]
Hey @jmccrae, sorry to ping you again on this.
Could you see if a quick change in the Rust code so could provide at least basic information about the error in the JSON file, instead of just the message "Data contains a JSON error"?

**Comment by frmichel** [comment]
Found it!
See next issue.
